### ISSUE TITLE
[Dynamic Entity Hider] Different setting in Wilderness

### ISSUE THREAD

**Issue by Gollum69** [Jbleezy/runelite-plugins#1]
If you are a typical ironman like me and play with players permanently off bc you are allergic to human contact it would be a nice setting if there was a separate wilderness option where you could change the number of visible players when in the wilderness, as currently I have to disable the plugin in the wildy or I'll get attacked by a clan of 10 invisible players to try and get my spade whilst I kill scorpia

**Comment by Jbleezy** [comment]
Added. efb17eacc2b1853225bd909ca1a4a1dfca40e960

**Comment by Z7-z** [comment]
love you
