### ISSUE TITLE
[Mouseover Text Disabler] Toggles on/off when going to other areas

### ISSUE THREAD

**Issue by MarniRS** [Jbleezy/runelite-plugins#2]
Seems like everytime you teleport away to another place or enter an instance it will toggle the command again on/off. 

Example gif; https://imgur.com/FNGTs0y

Havent tested thoroughly but in general it just seems to toggle everytime you go into another area.
Works as intended on login/hop though!

**Comment by Jbleezy** [comment]
Yeah I've noticed now it's not working all the time, I will look into a fix.

**Comment by Jbleezy** [comment]
Fixed. b965ec0884631fab7acdbc647a550ca774ed6f0c
