### ISSUE TITLE
[Mouseover Text Disabler] Allow mouseover text of clue rewards

### ISSUE THREAD

**Issue by Z7-z** [Jbleezy/runelite-plugins#3]
Currently when you open a clue casket nothing appears whatsoever when you hover over a clue reward, you can just close the interface down so the rewards appear in your inventory but alot of rewards I have no idea what they are and you kinda instinctively wanna hover over it to see what it is but you can't with this enabled, but I wanna keep it enabled since it gets rid of the otherwise useless top left text for everything else. I am also too lazy to turn the plugin on and off everytime I get a casket

**Comment by Jbleezy** [comment]
I think the better solution would be for the Mouse Tooltips plugin to show on the clue reward screen.
